environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '6'
    - nodejs_version: '7'
    - nodejs_version: '8'

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm --version
  - npm install

matrix:
  fast_finish: true

build: off

test_script:
  - node ./node_modules/jest-cli/bin/jest.js --config test/jest.json

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
